Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -21,43 +21,33 @@ keywords=(dpm dpq dvm ddebug_backtrace print_r var_dump debug_backtrace console\
 keywords_for_grep=$(printf "|%s" "${keywords[@]}")
 keywords_for_grep=${keywords_for_grep:1}
 
-# Directories and files to be excluded during search.
-exclude_dir_and_ext='\/features\/|\/contrib\/|\/devel\/|\/libraries\/|\/vendor\/|\.info$|\.png$|\.gif$|\.jpg$|\.ico$|\.patch$|\.htaccess$|\.sh$|\.ttf$|\.woff$|\.eot$|\.svg$'
-
 # Flag counter
 synatx_error_found=0
 debugging_function_found=0
 merge_conflict=0
 coding_standard_error=0
 
-# Check for PHP syntax
-# List php files added to commit
-php_files_changed=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep '\/modules\/custom\/|\/themes\/custom\/|\.php$|\.module$|\.inc$|\.install$|\.test$|\.profile$|\.theme$|\.js$|\.css$|\.info$|\.txt$'`
-if [ -n "$php_files_changed" ]
-then
-  for FILE in $php_files_changed; do
-  php -l $FILE > /dev/null 2>&1
-  compiler_result=$?
-  if [ $compiler_result -eq 255 ]
-  then
-    if [ $synatx_error_found -eq 0 ]
-    then
-      echo "${red}"
-      echo "# Compilation error(s):"
-      echo "-----------------------${reset}"
-    fi
-    synatx_error_found=1
-    `php -l $FILE > /dev/null`
-  fi
-  done
-fi
-
-# Check for debugging functions
-# List all files added to commit excluding the exceptions
-files_changed=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep -v $exclude_dir_and_ext | egrep '\/modules\/custom\/|\/themes\/custom\/|\.php$|\.module$|\.inc$|\.install$|\.test$|\.profile$|\.theme$|\.js$|\.css$|\.info$|\.txt$'`
+files_changed=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep '^modules/custom|^themes/custom' | egrep '\.php$|\.module$|\.inc$|\.install$|\.test$|\.profile$|\.theme$|\.js$|\.css$|\.info$|\.txt$'`
 if [ -n "$files_changed" ]
 then
-  for FILE in $files_changed ; do
+  for FILE in $files_changed; do
+    # Check for PHP syntax
+    # List php files added to commit
+    php -l $FILE > /dev/null 2>&1
+    compiler_result=$?
+    if [ $compiler_result -eq 255 ]
+    then
+      if [ $synatx_error_found -eq 0 ]
+      then
+        echo "${red}"
+        echo "# Compilation error(s):"
+        echo "-----------------------${reset}"
+      fi
+      synatx_error_found=1
+      `php -l $FILE > /dev/null`
+    fi
+    # Check for debugging functions
+    # List all files added to commit excluding the exceptions
     for keyword in "${keywords[@]}" ; do
       # Find debugging function exists in file diff one by one.
       pattern="^\+(.*)?$keyword(.*)?"
@@ -77,32 +67,9 @@ then
         }'
       fi
     done
-  done
-fi
-
-# Check for Drupal coding standards
-# List php files added to commit
-php_files_changed=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep -v $exclude_dir_and_ext | egrep '\/modules\/custom\/|\/themes\/custom\/|\.php$|\.module$|\.inc$|\.install$|\.test$|\.profile$|\.theme$|\.js$|\.css$|\.info$|\.txt$'`
-if [ -n "$php_files_changed" ]
-then
-  phpcs_result=`phpcs --standard=Drupal --report=csv $php_files_changed`
-  if [ "$phpcs_result" != "File,Line,Column,Type,Message,Source,Severity,Fixable" ]
-  then
-    echo "${red}"
-    echo "# Coding standard issue(s):"
-    echo "---------------------------${reset}"
-    phpcs --standard=Drupal $php_files_changed
-    coding_standard_error=1
-  fi
-fi
-
-# Check for merge conflict markers
-# List all files added to commit
-files_changed=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep '\/modules\/custom\/|\/themes\/custom\/|\.php$|\.module$|\.inc$|\.install$|\.test$|\.profile$|\.theme$|\.js$|\.css$|\.info$|\.txt$'`
-if [ -n "$files_changed" ]
-then
-  for FILE in $files_changed; do
-    # Find debugging function exists in file diff one by one.
+    # Check for merge conflict markers
+    # List all files added to commit
+    # Find merge conflict exists in file diff one by one.
     pattern="(<<<<|====|>>>>)+.*(\n)?"
     result_for_file=`egrep -in "$pattern" $FILE`
     if [ ! -z "$result_for_file" ]
@@ -117,6 +84,17 @@ then
       echo $FILE
     fi
   done
+  # Check for Drupal coding standards
+  # List php files added to commit
+  phpcs_result=`phpcs --standard=Drupal --report=csv $files_changed`
+  if [ "$phpcs_result" != "File,Line,Column,Type,Message,Source,Severity,Fixable" ]
+  then
+    echo "${red}"
+    echo "# Coding standard issue(s):"
+    echo "---------------------------${reset}"
+    phpcs --standard=Drupal $files_changed
+    coding_standard_error=1
+  fi
 fi
 
 # Decision maker
